create table management.HUA_ROLE
(
    id   int8 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
);
create table management.HUA_USER
(
    id                     int8 generated by default as identity,
    birth_date             date,
    created_date           timestamp   not null,
    email                  varchar(25) not null,
    last_modification_date timestamp,
    name                   varchar(20),
    password               varchar(50) not null,
    surname                varchar(20),
    username               varchar(25) not null,
    primary key (id)
);
create table management.user_role
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);
alter table if exists management.HUA_USER
    add constraint UK_foifti1tkmfx6civn1hhpy9mw unique (email);
alter table if exists management.HUA_USER
    add constraint UK_6sj80w5kgd7s32pyekacvm0bs unique (username);
alter table if exists management.user_role
    add constraint FK4dtax8dqn5q8erfpwpsfmlefy foreign key (role_id) references management.HUA_ROLE;
alter table if exists management.user_role
    add constraint FK9h21kuptkh88qcvyjil91efe0 foreign key (user_id) references management.HUA_USER;
