-- liquibase formatted sql

-- changeset role:1
create table management.HUA_ROLE2
(
    id   int8 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
);

-- changeset test:2
create table management.HUA_ROLE3
(
    id   int8 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
);