-- liquibase formatted sql

--changeset update-user-vat-number:1
alter table management.hua_user
    add mobile_number varchar(20);

alter table management.hua_user
    add vat_number varchar(20);

--changeset update-user-gender-marital:2
alter table management.hua_user
    add gender varchar(20);

alter table management.hua_user
    add marital_status varchar(20);

--changeset update-user-enums-date:3
alter table management.hua_user
    add job_status varchar(20);

alter table management.hua_user
    add employee_status varchar(20);

alter table management.hua_user
    add hire_date date;

--changeset update-user-numbers:4
alter table management.hua_user
    add work_number varchar(20);

alter table management.hua_user
    add home_number varchar(20);

alter table management.hua_user
    add employee_number bigint;

--changeset update-user-division:5
create table management.HUA_DIVISION
(
    ID   int8 generated by default as identity,
    name varchar(255),
    primary key (ID)
);
alter table if exists management.HUA_USER add column division_id int8;
alter table if exists management.HUA_USER add constraint FKt24r5ps8o4e5jnevnq9tvm4cc foreign key (division_id) references management.HUA_DIVISION;

--changeset update-user-location:6
create table management.HUA_LOCATION
(
    ID   int8 generated by default as identity,
    name varchar(255),
    primary key (ID)
);
alter table if exists management.HUA_USER add column location_id int8;
alter table if exists management.HUA_USER add constraint FKt24r5ps8o4e5jnevnq9tvm4qq foreign key (location_id) references management.HUA_LOCATION;