apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: 'geokall/api-management:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hua-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hua-management-secret
                  key: dbuser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hua-management-secret
                  key: dbpassword
          volumeMounts:
            - name: sqlvolume
              mountPath: "/sql"
              readOnly: true
      volumes:
        - name: sqlvolume
          secret:
            secretName: hua-sql-file-secret
            items:
              - key: init.sql
                path: initdb.sql #path means we rename it in our container