kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: managementapidata
spec:
  accessModes: [ ReadWriteOnce ]
  # storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 100Mi