# Won't be used since helm postgres create its own pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apidata
spec:
  accessModes: [ ReadWriteOnce ]
  # storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 100Mi